# Copyright 2024 Simprint. All rights reserved.
# Simprint 认证模块

source_set("auth") {
  sources = [
    "auth_manager.cc",
    "auth_manager.h",
    "startup_auth_checker.cc",
    "startup_auth_checker.h",
  ]

  deps = [
    "//base",
    "//simprint/console_log",
    "//simprint/eventbus",
  ]
}
