# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

assert(is_win || is_mac || is_linux || is_chromeos)

import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojo_bindings") {
  sources = [ "review_page.mojom" ]

  public_deps = [ "//mojo/public/mojom/base" ]

  webui_module_path = "/"
}

source_set("review") {
  sources = [
    "review_handler.cc",
    "review_handler.h",
    "review_ui.cc",
    "review_ui.h",
  ]

  defines = [ "SIMPRINT_FINGERPRINT_ENABLED" ]

  public_deps = [
    ":mojo_bindings",
    "//base",
    "//chrome/browser/profiles:profile",
    "//chrome/common",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
  ]

  deps = [
    "//chrome/browser/resources/review:resources",
    "//net",
    "//services/network/public/cpp",
    "//simprint/fingerprint",
    "//ui/webui",
  ]
}
