# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojo_bindings") {
  sources = [ "simprint_ip.mojom" ]
  webui_module_path = "/"
}

source_set("simprint_ip") {
  sources = [
    "simprint_ip_handler.cc",
    "simprint_ip_handler.h",
  ]

  deps = [
    ":mojo_bindings",
    "//base",
    "//chrome/browser/profiles:profile",
    "//mojo/public/cpp/bindings",
    "//net",
    "//services/network/public/cpp",
    "//services/network/public/mojom",
    "//url",
  ]
}
